{% set name = "dtaidistance" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9391d9348e03caa45939e377b85a30e903fb4f1beee25ece13d0ceebc52572f2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - cython
    - numpy
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - wheel
  run:
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - python

test:
  imports:
    - dtaidistance
    - dtaidistance.clustering
    - dtaidistance.dtw
    - dtaidistance.dtw_cc
    - dtaidistance.dtw_cc_numpy
    - dtaidistance.dtw_cc_omp  # [not linux]
    - dtaidistance.ed_cc

about:
  home: https://github.com/wannesm/dtaidistance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Distance measures for time series
  doc_url: https://dtaidistance.readthedocs.io/en/latest/
  dev_url: https://github.com/wannesm/dtaidistance

extra:
  recipe-maintainers:
    - wannesm
    - m-rossi
