{% set name = "dtaidistance" %}
{% set version = "2.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0da309e34a4a8cc47ba3c84cffa072361917bb411a4b61cf7d3ffc2d457cbff2

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - cython
    - numpy
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - wheel
  run:
    - {{ pin_compatible('numpy') }}
    - matplotlib-base >=3.0.0
    - python
    - scipy

test:
  imports:
    - dtaidistance
    - dtaidistance.clustering
    - dtaidistance.dtw
    - dtaidistance.dtw_cc
    - dtaidistance.dtw_cc_numpy
    - dtaidistance.dtw_cc_omp
    - dtaidistance.ed_cc

about:
  home: https://github.com/wannesm/dtaidistance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Distance measures for time series
  doc_url: https://dtaidistance.readthedocs.io/en/latest/
  dev_url: https://github.com/wannesm/dtaidistance

extra:
  recipe-maintainers:
    - wannesm
    - m-rossi
